services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-products-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
      - DB_NAME=products_db
      - PRECIO_USD=1435
      - PORT=3000
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - products-network

  mysql:
    image: mysql:8.0
    container_name: mysql-products-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=products_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot_password']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - products-network

networks:
  products-network:
    driver: bridge

volumes:
  mysql-data:
